version: '3.9'

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DJANGO_SETTINGS_MODULE=InfraTech.settings
    depends_on:
      - db
  
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: ["ng", "serve", "--host", "0.0.0.0"]
    depends_on:
      - backend

  db:
    image: postgres:16
    container_name: db
    environment:
      POSTGRES_DB: infratech
      POSTGRES_USER: infratech
      POSTGRES_PASSWORD: infratech
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
